apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: quay-enterprise

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- ../../../../../manifests/app/operators/quay-operator/base

resources:
- quay-og.yaml
- quay-namespace.yaml