apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: airlinepredictions

bases:
- ../../../../manifests/app/frontend/airline-prediction-stream/base
- ../../../../manifests/app/frontend/airline-prediction-generator/base

resources:
- namespace.yaml