apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/strimzi-kafka-operator.myproject-dev: ''
spec:
  channel: strimzi-0.19.x
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
