apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- ../../../../../manifests/app/operators/opendatahub-operator/base
- ../../../../../manifests/app/operators/opendatahub-operator/base/cr

resources:
- kubeflow-namespace.yaml
- odh-namespace.yaml