apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: openshift-metering

bases:
- ../../../../../manifests/app/operators/metering-operator/base

resources:
- namespace.yaml