apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: manuela-quickstart-messaging

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- ../../../../../manifests/app/operators/amq-broker-operator/base

resources:
- manuela-namespace.yaml