apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
  namespace: codeready
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  server:
    cheImageTag: ''
    cheFlavor: codeready
    devfileRegistryImage: ''
    pluginRegistryImage: ''
    tlsSupport: false
    selfSignedCert: true
  database:
    externalDb: false
    #chePostgresHostName: ''
    #chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    #chePostgresDb: ''
  auth:
    openShiftoAuth: false
    identityProviderImage: ''
    externalIdentityProvider: false
    #identityProviderURL: ''
    #identityProviderRealm: ''
    #identityProviderClientId: ''
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
