# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../aws/

patchesStrategicMerge:
- patches/manuela-line-dashboard-app.yaml
- patches/manuela-machine-sensor-app.yaml